# Generated by Django 5.0.7 on 2024-07-09 20:24

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Chip",
            fields=[
                ("numero_chip", models.AutoField(primary_key=True, serialize=False)),
                ("compania", models.CharField(max_length=100)),
                ("numero", models.CharField(max_length=15)),
                ("correo", models.EmailField(max_length=254)),
                ("contraseña", models.CharField(max_length=100)),
                ("contraseña_plataforma", models.CharField(max_length=100)),
                ("usuario_plataforma", models.CharField(max_length=100)),
            ],
        ),
    ]
